spring.application.name=survey-service


#postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/survey-service
spring.datasource.username=postgres
spring.datasource.password=Aayush@54321

#redis
# Redis Configuration

spring.data.redis.url=redis://default:n1C9scwv8RJ0fcySLrYgmrnBBt8qIMh8@adoring-kettle-disciplined-94852.db.redis.io:12187

